Test
RoadToSoftwareFactory/swi-2018 pull request #18
Opened 2018-10-11 08:45 UTC by josefsys

bylo to bezva

2018-10-11 08:46 UTC, josefsys commented
comment

2018-10-16 13:51 UTC, Hyperkid123 requested changes
You are also missing third commit with come git diff.

2018-10-16 13:51 UTC, Hyperkid123 commented on firstFile/secFile
> +efisfbu
This does not look like hash of commit. Also it was supposed to be in the same file as your joke (btw the joke is good)

2018-11-09 11:53 UTC, Hyperkid123 requested changes
You have added all the changes that were made on master branch as your. You can fix it by rebasing and removing commits that are not yours.

2018-12-03 09:38 UTC, Hyperkid123 approved these changes

2019-05-30 13:48 UTC, closed without merging